---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: reddit-ui
  namespace: demo-flagger
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/ignore: "false"
    fluxcd.io/tag.chart-image: semver:~0.1
spec:
  rollback:
    # If set, will perform rollbacks for this release.
    enable: true
    # If set, will force resource update through delete/recreate if
    # needed.
    force: true
  releaseName: reddit-ui
  chart:
    git: git@github.com:czm41k/gitops-flux-hw
    path: charts/ui
    ref: master
  values:
    image:
      repository: czm41k/ui
      tag: 0.1.3
    service:
      enabled: true
