---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reddit-ui
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: reddit.104.199.20.0.nip.io
      http:
        paths:
          - backend:
              serviceName: reddit-ui
              servicePort: {{ .Values.service.internalPort }}
...
