---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: reddit.104.199.20.0.nip.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "ui.fullname" . }}
          servicePort: {{ .Values.service.internalPort }}
...
